// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using uService.Database;

#nullable disable

namespace uService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240804072949_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.32");

            modelBuilder.Entity("uService.Models.Objednavka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumVytvoreni")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StavObjednavky")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Objednavky");
                });

            modelBuilder.Entity("uService.Models.PolozkaObjednavky", b =>
                {
                    b.Property<string>("NazevZbozi")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjednavkaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("TEXT");

                    b.Property<int>("PocetKusu")
                        .HasColumnType("INTEGER");

                    b.HasKey("NazevZbozi", "ObjednavkaId");

                    b.HasIndex("ObjednavkaId");

                    b.ToTable("PolozkyObjednavky");
                });

            modelBuilder.Entity("uService.Models.PolozkaObjednavky", b =>
                {
                    b.HasOne("uService.Models.Objednavka", "Objednavka")
                        .WithMany("PolozkyObjednavky")
                        .HasForeignKey("ObjednavkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objednavka");
                });

            modelBuilder.Entity("uService.Models.Objednavka", b =>
                {
                    b.Navigation("PolozkyObjednavky");
                });
#pragma warning restore 612, 618
        }
    }
}
